services:
  - type: cron
    name: twfuture-alert-bot
    runtime: python
    schedule: "*/2 * * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
